Repository OCamlPro/alt-ergo, pull requests merged in 2020-12, with the labels that each got.

#358 Doc-Alt-Ergo
  .travis.yml
  Makefile
  docs/sphinx_docs/API/index.md
  docs/sphinx_docs/About/changes.md
  docs/sphinx_docs/About/index.rst
  docs/sphinx_docs/About/license.md
  docs/sphinx_docs/Dev/architecture.md
  docs/sphinx_docs/Dev/contributing.md
  docs/sphinx_docs/Dev/index.rst
  docs/sphinx_docs/Input_file_formats/Native/00_summary.md
  docs/sphinx_docs/Input_file_formats/Native/01_declaration_of_symbols.md
  docs/sphinx_docs/Input_file_formats/Native/02_types/02_01_builtin.md
  docs/sphinx_docs/Input_file_formats/Native/02_types/02_02_user_defined.md
  docs/sphinx_docs/Input_file_formats/Native/02_types/index.rst
  docs/sphinx_docs/Input_file_formats/Native/03_declaration_of_axioms.md
  docs/sphinx_docs/Input_file_formats/Native/04_setting_goals.md
  docs/sphinx_docs/Input_file_formats/Native/05_theories.md
  docs/sphinx_docs/Input_file_formats/Native/06_control_flow.md
  docs/sphinx_docs/Input_file_formats/Native/07_syntax_of_declarations_and_expressions.md
  docs/sphinx_docs/Input_file_formats/Native/TODOs.md
  docs/sphinx_docs/Input_file_formats/Native/index.rst
  docs/sphinx_docs/Input_file_formats/index.rst
  docs/sphinx_docs/Install/deps.png
  docs/sphinx_docs/Install/index.md
  docs/sphinx_docs/Plugins/ab_why3.md
  docs/sphinx_docs/Usage/index.md
  docs/sphinx_docs/_static/css/dac_theme_modif.css
  docs/sphinx_docs/conf.py
  docs/sphinx_docs/index.rst
  docs/sphinx_docs/requirements.txt
  rsc/extra/deploy_doc.sh
  rsc/extra/index.adoc
  rsc/extra/travis_doc_test.sh
  src/lib/structures/errors.mli
Labels: documentation

#372 Add option `--instantiation-heuristic` that can enable lighter or heavier instantiation
  src/bin/common/parse_command.ml
  src/bin/gui/main_gui.ml
  src/lib/reasoners/fun_sat.ml
  src/lib/reasoners/satml_frontend.ml
  src/lib/util/options.ml
  src/lib/util/options.mli
Labels: dev

#378 Clean md file in root dir. Use files in docs section instead
  CHANGES
  CONTRIBUTING.md
  COPYING.md
  INSTALL.md
  USAGE.md
Labels: documentation

#371 Incremental smt2
  alt-ergo-parsers.opam
  dune-project
  examples/lib_usage.ml
  src/bin/gui/annoted_ast.ml
  src/bin/gui/main_gui.ml
  src/bin/text/main_text.ml
  src/lib/frontend/cnf.ml
  src/lib/frontend/frontend.ml
  src/lib/frontend/frontend.mli
  src/lib/frontend/input.ml
  src/lib/frontend/input.mli
  src/lib/frontend/parsed_interface.ml
  src/lib/frontend/parsed_interface.mli
  src/lib/frontend/typechecker.ml
  src/lib/frontend/typechecker.mli
  src/lib/reasoners/fun_sat.ml
  src/lib/reasoners/instances.ml
  src/lib/reasoners/instances.mli
  src/lib/reasoners/intervalCalculus.ml
  src/lib/reasoners/matching.ml
  src/lib/reasoners/matching.mli
  src/lib/reasoners/matching_types.mli
  src/lib/reasoners/sat_solver_sig.ml
  src/lib/reasoners/sat_solver_sig.mli
  src/lib/reasoners/satml.ml
  src/lib/reasoners/satml.mli
  src/lib/reasoners/satml_frontend.ml
  src/lib/structures/commands.ml
  src/lib/structures/commands.mli
  src/lib/structures/errors.ml
  src/lib/structures/errors.mli
  src/lib/structures/parsed.ml
  src/lib/structures/parsed.mli
  src/lib/structures/satml_types.ml
  src/lib/structures/satml_types.mli
  src/lib/structures/typed.ml
  src/lib/structures/typed.mli
  src/lib/util/steps.ml
  src/lib/util/steps.mli
  src/lib/util/util.ml
  src/lib/util/util.mli
  src/parsers/psmt2_to_alt_ergo.ml
Labels: dev

#388 Clean greedy instantiation heuristic in satml_frontend
  src/lib/reasoners/satml_frontend.ml
Labels: dev

#352 disable deductions by congruence closure on record symbols
  src/lib/reasoners/records.ml
Labels: enhancement
