Repository OCamlPro/alt-ergo, pull requests merged in 2023-11, with the labels that each got.

#923 Update the lock file
  Makefile
  alt-ergo-lib.opam.locked
Labels: build

#866 Use stdcompat to support old OCaml version
  alt-ergo-lib.opam
  dune-project
  src/bin/common/input_frontend.ml
  src/bin/common/parse_command.ml
  src/bin/common/solving_loop.ml
  src/lib/dune
  src/lib/reasoners/bitv.ml
  src/lib/reasoners/satml.ml
  src/lib/structures/symbols.ml
  src/lib/util/compat.ml
  src/lib/util/compat.mli
  src/lib/util/lists.ml
  src/lib/util/lists.mli
Labels: build

#932 Bubble printing model
  src/bin/common/solving_loop.ml
  src/bin/js/worker_js.ml
  src/lib/frontend/frontend.ml
  src/lib/frontend/frontend.mli
  src/lib/reasoners/sat_solver_sig.ml
  src/lib/reasoners/sat_solver_sig.mli
Labels: frontend

#960 Remove unused symbols `Reach` and `Fixed`
  src/lib/reasoners/arith.ml
  src/lib/structures/modelMap.ml
  src/lib/structures/symbols.ml
  src/lib/structures/symbols.mli
Labels: clean-up

#952 Add a SMT-LIB compliant printer for `Expr`
  src/lib/frontend/models.ml
  src/lib/structures/expr.ml
  src/lib/structures/symbols.ml
  src/lib/structures/symbols.mli
Labels: models

#965 Fix the locked file
  .github/workflows/build.yml
  .github/workflows/build_js.yml
  alt-ergo-lib.opam
  alt-ergo-lib.opam.locked
  alt-ergo-lib.opam.template
Labels: build

#992 cleanup: Remove one layer of unique variable identifiers
  src/lib/structures/expr.ml
  src/lib/structures/expr.mli
  src/lib/structures/var.ml
  src/lib/structures/var.mli
Labels: clean-up

#991 cleanup: Remove "fake" symbols and trigger guards
  src/lib/frontend/cnf.ml
  src/lib/frontend/d_cnf.ml
  src/lib/reasoners/instances.ml
  src/lib/reasoners/intervalCalculus.ml
  src/lib/structures/expr.ml
  src/lib/structures/expr.mli
  src/lib/structures/symbols.ml
  src/lib/structures/symbols.mli
Labels: clean-up

#981 Simplify numerical expressions in SMT-LIB printers
  src/lib/structures/expr.ml
Labels: frontend
