Repository OCamlPro/alt-ergo, pull requests merged in 2023-10, with the labels that each got.

#858 Remove infer_input_format option
  src/bin/common/parse_command.ml
  src/bin/common/solving_loop.ml
  src/bin/js/options_interface.ml
  src/lib/util/options.ml
  src/lib/util/options.mli
  src/parsers/parsers.ml
Labels: clean-up

#857 Make Dolmen the default frontend
  CHANGES.md
  docs/sphinx_docs/Input_file_formats/Native/02_types/02_01_builtin.md
  docs/sphinx_docs/Input_file_formats/SMT-LIB2/index.md
  docs/sphinx_docs/Usage/index.md
  src/bin/common/parse_command.ml
  src/lib/util/options.ml
  tests/cram.t/run.t
Labels: frontend

#862 Add a Pygments lexer for the Alt-Ergo language
  .gitignore
  docs/sphinx_docs/alt_ergo_lexer.py
  docs/sphinx_docs/conf.py
Labels: documentation

#870 Remove misleading comment
  src/lib/reasoners/intervalCalculus.ml
Labels: clean-up

#887 Using `dune build @check` to build the project
  Makefile
Labels: build

#907 CHANGES log for the release v2.5.2
  CHANGES.md
Labels: documentation

#915 Document `Th_util.lit_origin`
  src/lib/reasoners/th_util.mli
Labels: documentation

#868 The formulae `top` and `bot` are constant
  src/lib/reasoners/ccx.ml
  src/lib/reasoners/ccx.mli
  src/lib/reasoners/intervalCalculus.ml
  src/lib/reasoners/shostak.ml
  src/lib/reasoners/shostak.mli
  src/lib/reasoners/sig.mli
  src/lib/reasoners/theory.ml
  src/lib/reasoners/uf.ml
  src/lib/reasoners/uf.mli
  src/lib/structures/xliteral.ml
  src/lib/structures/xliteral.mli
Labels: clean-up

#871 Documentation of the Enum theory
  src/lib/reasoners/adt_rel.ml
  src/lib/reasoners/enum.ml
  src/lib/reasoners/enum_rel.ml
  src/lib/reasoners/intervalCalculus.ml
Labels: documentation

#916 feat: Option --optimize
  src/bin/common/parse_command.ml
  src/bin/common/solving_loop.ml
  src/lib/reasoners/sat_solver.mli
  src/lib/util/options.ml
  src/lib/util/options.mli
Labels: frontend, optimization

#905 Uniformization of internal identifiers generation
  src/lib/frontend/typechecker.ml
  src/lib/reasoners/arith.ml
  src/lib/reasoners/fun_sat.ml
  src/lib/reasoners/satml_frontend.ml
  src/lib/reasoners/uf.ml
  src/lib/structures/expr.ml
  src/lib/structures/expr.mli
  src/lib/structures/symbols.ml
  src/lib/structures/symbols.mli
  src/lib/util/hstring.ml
  src/lib/util/hstring.mli
Labels: clean-up
