Repository OCamlPro/alt-ergo, pull requests merged in 2023-09, with the labels that each got.

#797 Backporting 2.5.0 ter
  alt-ergo-lib.opam
  dune
  dune-project
  src/plugins/AB-Why3/preludes/dune
  src/preludes/dune
Labels: backporting

#802 Use fmt 0.9.0 to prevent conflict with the result library
  alt-ergo-lib.opam
  dune-project
Labels: build, backporting

#805 Deprecate the option --use-underscore
  CHANGES.md
  src/bin/common/parse_command.ml
Labels: frontend

#804 Replace dummy values in Model by abstract values
  src/lib/frontend/models.ml
  tests/cram.t/run.t
  tests/issues/555.models.expected
  tests/models/records/record1.models.expected
Labels: enhancement, frontend

#803 Test AE on 4.08.1 and 4.14.1
  .github/workflows/build.yml
  CHANGES.md
  alt-ergo-lib.opam
  alt-ergo-parsers.opam
  alt-ergo.opam
  dune-project
Labels: build

#811 Use fresh names for all the abstract values
  src/lib/frontend/models.ml
  tests/cram.t/run.t
  tests/issues/555.models.expected
Labels: frontend

#812 Removing useless line in the cram tests
  tests/cram.t/run.t
Labels: bug, build, backporting

#815 Backporting 2.5.0 final
  alt-ergo-lib.opam
  dune-project
Labels: build

#814 Result conflict and ppxlib
  alt-ergo-lib.opam
  dune-project
Labels: build, backporting

#817 Backporting 2.5.0 finaaaal
  alt-ergo-lib.opam
  dune-project
Labels: build

#816 Increase minimal version of Zarith
  alt-ergo-lib.opam
  dune-project
Labels: build, backporting

#572 clean shostak
  src/lib/reasoners/shostak.ml
Labels: dev, documentation

#826 Add a new example for model generation
  docs/sphinx_docs/Usage/index.md
Labels: documentation

#818 Deploy the documentation of the main branch
  .github/workflows/documentation.yml
Labels: documentation, backporting
