Repository OCamlPro/alt-ergo, pull requests merged in 2023-05, with the labels that each got.

#515 Fixing issue 52
  src/lib/reasoners/bitv.ml
Labels: enhancement

#600 Remove nums
  alt-ergo-lib.opam
  configure.ml
  dune-project
  src/bin/gui/annoted_ast.ml
  src/lib/dune
  src/lib/frontend/cnf.ml
  src/lib/frontend/parsed_interface.mli
  src/lib/frontend/typechecker.ml
  src/lib/index.mld
  src/lib/structures/parsed.ml
  src/lib/structures/parsed.mli
  src/lib/structures/typed.ml
  src/lib/structures/typed.mli
  src/lib/util/numbers.ml
  src/lib/util/numbers.mli
  src/lib/util/numbersInterface.mli
  src/lib/util/numsNumbers.ml
  src/lib/util/numsNumbers.mli
  src/lib/util/zarithNumbers.ml
  src/lib/util/zarithNumbers.mli
  src/parsers/native_lexer.mll
  src/parsers/native_parser.mly
  src/parsers/psmt2_to_alt_ergo.ml
Labels: build

#602 Refactoring the debug commands
  src/bin/common/parse_command.ml
  src/lib/util/options.mli
Labels: enhancement, frontend

#606 Fix the leak memory in Vec
  src/lib/util/vec.ml
Labels: bug

#609 Fix model generation
  src/lib/util/options.ml
Labels: bug
