Repository OCamlPro/alt-ergo, pull requests merged in 2023-07, with the labels that each got.

#714 Create timers
  src/lib/reasoners/ite_rel.ml
  src/lib/util/timers.ml
  src/lib/util/timers.mli
Labels: bug

#739 Fix issue 719
  src/bin/common/solving_loop.ml
  tests/models/issues/719.models.expected
  tests/models/issues/719.models.smt2
Labels: bug, frontend

#742 Remove plateform-dependent message in the cram test
  tests/cram.t/run.t
Labels: build

#747 Temporary fix of issue 744
  src/lib/frontend/d_cnf.ml
Labels: bug, frontend

#745 Partial support of the primitive bvnot
  src/lib/dune
  src/lib/reasoners/bitv.ml
  tests/bitv/testfile-bvnot.dolmen.expected
  tests/bitv/testfile-bvnot.dolmen.smt2
Labels: enhancement

#755 Issue 705
  src/lib/frontend/models.ml
  src/lib/structures/modelMap.ml
  src/lib/structures/modelMap.mli
Labels: frontend

#760 Update dependencies
  alt-ergo-lib.opam
  alt-ergo-lib.opam.template
  docs/sphinx_docs/Install/index.md
  dune-project
Labels: build

#762 [doc] Document the floating-point and bitvector primitives
  docs/sphinx_docs/About/changes.md
  docs/sphinx_docs/Input_file_formats/Native/02_types/02_01_builtin.md
  docs/sphinx_docs/Input_file_formats/Native/05_theories.md
  docs/sphinx_docs/Input_file_formats/SMT-LIB2/index.md
  docs/sphinx_docs/Input_file_formats/index.rst
  docs/sphinx_docs/Plugins/ab_why3.md
  docs/sphinx_docs/Usage/index.md
  src/bin/text/index.mld
Labels: documentation

#764 [frontend] Use the dolmen frontend by default with --produce-models
  src/bin/common/parse_command.ml
Labels: frontend

#765 Clean up documentation
  docs/sphinx_docs/Input_file_formats/index.rst
  docs/sphinx_docs/_static/.gitkeep
  docs/sphinx_docs/_static/css/dac_theme_modif.css
  docs/sphinx_docs/conf.py
Labels: documentation

#766 Frontend documentation
  docs/sphinx_docs/Usage/index.md
Labels: documentation

#759 Update model documentation
  docs/sphinx_docs/Usage/index.md
Labels: documentation

#769 Add blocks for the notes
  docs/sphinx_docs/Input_file_formats/index.rst
  docs/sphinx_docs/Usage/index.md
Labels: documentation

#773 Remove useless template
  alt-ergo-js.opam.template
Labels: build
