Repository OCamlPro/alt-ergo, pull requests merged in 2023-04, with the labels that each got.

#560 Fix CI
  alt-ergo-js.opam
  dune-project
  src/bin/js/dune
  src/lib/missing_primitives.js
Labels: bug, build

#562 [arith] Add contextual explanation when tightening equalities
  src/lib/reasoners/intervalCalculus.ml
  tests/issues/479.expected
  tests/issues/479.smt2
Labels: bug

#571 Re-add (version dev) to dune-project
  alt-ergo-js.opam
  alt-ergo-lib.opam
  alt-ergo-parsers.opam
  alt-ergo.opam
  altgr-ergo.opam
  dune-project
Labels: build

#574 Use dune-build-info for version number (2.4.3)
  .gitignore
  Makefile
  alt-ergo-lib.opam
  dune-project
  src/bin/text/dune
  src/lib/dune
  src/lib/util/version.ml
Labels: build

#577 Update documentation 2.4.3
  docs/sphinx_docs/Install/index.md
Labels: documentation

#559 Prevent tests from running during the build passes
  Makefile
  tools/gentest.ml
Labels: build

#583 CI fix for dune-build-info
  .github/workflows/build_docker.yml
  .github/workflows/build_js.yml
  .github/workflows/build_macos.yml
  .github/workflows/build_make.yml
  .github/workflows/build_ubuntu.yml
  .github/workflows/build_windows.yml
  .github/workflows/documentation.yml
  Makefile
  tests/slow/issues/505/testfile_1.ae
  tests/slow/issues/505/testfile_1.expected
  tests/slow/issues/505/testfile_2.ae
  tests/slow/issues/505/testfile_2.expected
  tests/slow/issues/505/testfile_3.ae
  tests/slow/issues/505/testfile_3.expected
  tests/slow/issues/505/testfile_4.ae
  tests/slow/issues/505/testfile_4.expected
  tests/slow/issues/505/testfile_5.ae
  tests/slow/issues/505/testfile_5.expected
  tests/slow/issues/505/testfile_6.ae
  tests/slow/issues/505/testfile_6.expected
  tests/slow/issues/505/testfile_7.ae
  tests/slow/issues/505/testfile_7.expected
  tests/slow/issues/505/testfile_8.ae
  tests/slow/issues/505/testfile_8.expected
  tests/slow/issues/505/testfile_9.ae
  tests/slow/issues/505/testfile_9.expected
  tools/gentest.ml
Labels: build

#592 Fix zarith dependency
  alt-ergo-lib.opam
  docs/sphinx_docs/Install/index.md
  dune-project
  src/dune
Labels: build

#595 Clarify licenses
  docs/sphinx_docs/About/licenses/CeCILL-C-License-v1.txt
  docs/sphinx_docs/About/licenses/License.OCamlPro
  docs/sphinx_docs/About/licenses/License.OCamlPro.Club
  docs/sphinx_docs/About/licenses/index.rst
  src/bin/gui/connected_ast.ml
  src/bin/gui/main_gui.ml
  src/lib/reasoners/shostak.ml
Labels: documentation

#593 Removing alt-ergo-js.opam
  .github/workflows/build_js.yml
  .github/workflows/build_make.yml
  Makefile
  alt-ergo-js.opam
  docs/sphinx_docs/Install/index.md
  dune-project
  src/bin/js/dune
Labels: build
