Repository OCamlPro/alt-ergo, pull requests merged in 2023-12, with the labels that each got.

#996 Box at toplevel in SMT-LIB printer
  src/lib/structures/expr.ml
Labels: enhancement, frontend

#827 Release workflow
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: build, backlog

#607 New vec module
  src/lib/reasoners/satml.ml
  src/lib/structures/satml_types.ml
  src/lib/structures/satml_types.mli
  src/lib/util/iheap.ml
  src/lib/util/vec.ml
  src/lib/util/vec.mli
  src/plugins/fm-simplex/simplex.ml
Labels: enhancement

#1009 Wrong destructor for mutually recursive ADT
  src/lib/frontend/d_cnf.ml
  src/lib/structures/ty.mli
Labels: bug, frontend

#1006 Make the `Heap` module polymorphic
  rsc/extra/subgraphs.dot
  src/lib/dune
  src/lib/index.mld
  src/lib/reasoners/satml.ml
  src/lib/reasoners/satml_frontend.ml
  src/lib/structures/satml_types.ml
  src/lib/structures/satml_types.mli
  src/lib/util/heap.ml
  src/lib/util/heap.mli
  src/lib/util/iheap.ml
  src/lib/util/vec.ml
  src/lib/util/vec.mli
Labels: clean-up

#995 doc(CDCL): Document the CDCL-Tableaux solver
  src/lib/reasoners/satml.ml
Labels: documentation

#1017 Removing testers in the ADT Shostak theory
  src/lib/reasoners/adt.ml
  src/lib/reasoners/adt.mli
  src/lib/reasoners/adt_rel.ml
Labels: clean-up
