Repository OCamlPro/alt-ergo, pull requests merged in 2024-03, with the labels that each got.

#1052 fix(CI): Use lockfile for all workflows
  .github/workflows/documentation.yml
  .github/workflows/linter.yml
Labels: build

#1050 fix(build): Require dolmen 0.9
  dune-project
Labels: build

#1048 Do not hardcode Dynlink error in test output
  tests/cram.t/run.t
Labels: build

#1040 cleanup(CP): Simplify constraint handling
  src/lib/reasoners/bitv_rel.ml
  src/lib/reasoners/rel_utils.ml
Labels: clean-up

#1062 Update `Lib_usage.ml`
  dune
  examples/dune
  examples/lib_usage.ml
Labels: build

#1071 `ml_z_extract_small` is available in `zarith_stubs_js` v0.16.1
  .github/workflows/build_js.yml
  Makefile
  src/lib/missing_primitives.js
Labels: build

#1072 Fix js-deps target
  Makefile
Labels: build

#1070 Sort trigger patterns before caching
  src/lib/reasoners/matching.ml
  src/lib/util/lists.ml
  src/lib/util/lists.mli
Labels: performance

#1075 Fix wrong documentation of `Tadt`
  src/lib/structures/ty.mli
Labels: documentation

#1045 feat: Statically linked binary releases
  .github/workflows/build_docker.yml
  .github/workflows/build_static.yml
  src/bin/text/dune
  src/bin/text/flags.dune
  src/bin/text/gen-link-flags.sh
Labels: build

#1076 Prevent from adding dependencies of OCaml 5 in the lock file
  Makefile
Labels: build
