Repository OCamlPro/alt-ergo, pull requests merged in 2024-07, with the labels that each got.

#1149 Bump the version of Dolmen to 0.10
  alt-ergo-lib.opam.locked
  nix/sources.json
  src/lib/frontend/d_cnf.ml
Labels: build

#1153 Use Dolmen attribute to store well founded order
  src/lib/frontend/d_cnf.ml
  src/lib/frontend/typechecker.ml
  src/lib/reasoners/adt.ml
  src/lib/reasoners/adt.mli
  src/lib/reasoners/adt_rel.ml
  src/lib/reasoners/fun_sat.ml
  src/lib/reasoners/records.ml
  src/lib/reasoners/satml_frontend.ml
  src/lib/reasoners/theory.ml
  src/lib/structures/expr.ml
  src/lib/structures/expr.mli
  src/lib/structures/fpa_rounding.ml
  src/lib/structures/symbols.ml
  src/lib/structures/symbols.mli
  src/lib/structures/ty.ml
  src/lib/structures/ty.mli
  src/lib/structures/typed.ml
  src/lib/structures/typed.mli
  src/lib/structures/uid.ml
  src/lib/structures/uid.mli
  src/lib/structures/xliteral.ml
  src/lib/structures/xliteral.mli
  src/lib/util/nest.ml
  src/lib/util/nest.mli
Labels: clean-up

#1167 Remove prerelease flags
  .github/workflows/build.yml
  .github/workflows/build_js.yml
  .github/workflows/build_static.yml
  .github/workflows/documentation.yml
  .github/workflows/linter.yml
  .github/workflows/release.yml
Labels: build

#1175 chore: Support bytecode-only environments
  alt-ergo-lib.opam.locked
  alt-ergo-plugin-ab-why3.opam
  alt-ergo-plugin-ab-why3.opam.template
Labels: build

#1179 perf: Improve performance of literal de-duplication
  src/lib/reasoners/adt_rel.ml
  src/lib/reasoners/ccx.ml
  src/lib/reasoners/rel_utils.ml
Labels: performance

#1182 Remove invalid expected file
  tests/dolmen/bitv/bv2nat_bvnot_range.dolmen.expected.
Labels: build

#1184 Use Unix eof for shell scripts
  .gitattributes
Labels: build

#1186 Use Unix eof for shell scripts
  .gitattributes
Labels: build

#1187 Fix MacOS static build
  src/bin/text/gen-link-flags.sh
Labels: build

#1189 Rewrite `gen_link_flags` in OCaml
  src/bin/text/dune
  src/bin/text/gen-link-flags.sh
  src/bin/text/gen_link_flags.ml
Labels: build

#1191 Get rid of `stdcompat`
  CHANGES.md
  alt-ergo-lib.opam
  alt-ergo-lib.opam.locked
  default.nix
  dune-project
  shell.nix
  src/bin/common/input_frontend.ml
  src/bin/common/parse_command.ml
  src/bin/common/solving_loop.ml
  src/bin/text/dune
  src/bin/text/gen_link_flags.ml
  src/lib/dune
  src/lib/frontend/d_cnf.ml
  src/lib/frontend/typechecker.ml
  src/lib/index.mld
  src/lib/reasoners/adt.ml
  src/lib/reasoners/adt_rel.ml
  src/lib/reasoners/bitv.ml
  src/lib/reasoners/bitv_rel.ml
  src/lib/reasoners/intervals.ml
  src/lib/reasoners/intervals_core.ml
  src/lib/reasoners/records.ml
  src/lib/reasoners/satml.ml
  src/lib/reasoners/satml_frontend.ml
  src/lib/structures/expr.ml
  src/lib/structures/modelMap.ml
  src/lib/structures/symbols.ml
  src/lib/structures/ty.ml
  src/lib/util/compat.ml
  src/lib/util/compat.mli
  src/lib/util/my_list.ml
  src/lib/util/my_list.mli
  src/lib/util/my_unix.ml
  src/lib/util/my_unix.mli
  src/lib/util/options.ml
  src/lib/util/timers.ml
Labels: build
