Repository OCamlPro/alt-ergo, pull requests merged in 2024-01, with the labels that each got.

#1020 Clean up documentation of the SAT API
  src/bin/js/worker_js.ml
  src/lib/reasoners/fun_sat.ml
  src/lib/reasoners/fun_sat.mli
  src/lib/reasoners/fun_sat_frontend.ml
  src/lib/reasoners/sat_solver_sig.ml
  src/lib/reasoners/sat_solver_sig.mli
  src/lib/reasoners/satml_frontend.ml
Labels: documentation

#1025 fix(arith): Do not overly tighten bounds over infinite domains
  src/lib/reasoners/intervalCalculus.ml
  tests/issues/777.models.expected
  tests/models/uf/uf2.models.expected
Labels: bug

#1029 cleanup: Make `Vec.shrink` take the new length
  src/lib/reasoners/satml.ml
  src/lib/util/heap.ml
  src/lib/util/vec.ml
Labels: clean-up
