Repository OCamlPro/alt-ergo, pull requests merged in 2024-08, with the labels that each got.

#1200 Ignore :reproducible-resource-limit on non-Unix plateform
  src/bin/common/solving_loop.ml
Labels: windows

#1202 Remove warnings
  src/lib/reasoners/arrays_rel.ml
  src/lib/reasoners/fun_sat.mli
  src/lib/reasoners/sat_solver_sig.ml
  src/lib/reasoners/sat_solver_sig.mli
  src/lib/reasoners/satml.ml
  src/lib/reasoners/satml_frontend.ml
  src/lib/reasoners/satml_frontend_hybrid.mli
  src/lib/util/nest.ml
Labels: clean-up

#1203 Restore Windows CI on Cygwin
  .github/workflows/build.yml
  tests/bitv/testfile-qfbv-timeout.unix.dolmen.expected
  tests/bitv/testfile-qfbv-timeout.unix.dolmen.smt2
  tools/gentest.ml
Labels: build

#1192 fix(BV): Internalize sign_extend and repeat
  src/lib/reasoners/bitv.ml
  src/lib/structures/expr.ml
  src/lib/structures/symbols.ml
  src/lib/structures/symbols.mli
  tests/bitv/testfile-repeat-001.expected
  tests/bitv/testfile-repeat-001.smt2
  tests/bitv/testfile-repeat-002.expected
  tests/bitv/testfile-repeat-002.smt2
  tests/bitv/testfile-sign-extend-001.expected
  tests/bitv/testfile-sign-extend-001.smt2
  tests/bitv/testfile-sign-extend-002.expected
  tests/bitv/testfile-sign-extend-002.smt2
  tests/bitv/testfile-sign-extend-003.expected
  tests/bitv/testfile-sign-extend-003.smt2
  tests/bitv/testfile-sign-extend-004.expected
  tests/bitv/testfile-sign-extend-004.smt2
Labels: performance, bit-vectors

#1208 Remove gtk-lang file
  docs/gtk-lang/alt-ergo.lang
Labels: clean-up

#1204 Deprecate debug flags
  rsc/extra/worker_json_example.json
  src/bin/common/parse_command.ml
  src/bin/js/options_interface.ml
  src/bin/js/worker_interface.ml
  src/bin/js/worker_interface.mli
  src/lib/util/options.ml
  src/lib/util/options.mli
Labels: clean-up

#1207 Use logs in `Adt_rel`
  src/lib/reasoners/adt_rel.ml
Labels: frontend

#1216 Add documentation for Windows support
  docs/sphinx_docs/Install/index.md
Labels: documentation, windows

#1219 Remove some polymorphic hashtables
  src/lib/reasoners/uf.ml
  src/lib/structures/expr.ml
  src/lib/structures/expr.mli
Labels: bug

#1223 Wrap the library Alt_ergo_prelude
  src/alt_ergo_prelude.ml
  src/dune
  src/lib/dune
Labels: build

#1227 chore(warnings): Drop acts_add_lit_view
  src/lib/reasoners/bitv_rel.ml
Labels: clean-up

#1224 fix(opt): Only perform optimization when building a model
  src/lib/reasoners/satml.ml
  src/lib/reasoners/theory.ml
  src/lib/reasoners/theory.mli
Labels: bug, optimization

#1226 fix(BV): Do not build unnormalized values in zero_extend
  src/lib/reasoners/bitv.ml
  src/lib/reasoners/bitv.mli
  src/lib/reasoners/bitv_rel.ml
Labels: bug, 💣 soundness, bit-vectors
