Repository OCamlPro/alt-ergo, pull requests merged in 2025-03, with the labels that each got.

#1266 Remove labels on Symbols and Xliteral
  src/lib/reasoners/ccx.ml
  src/lib/reasoners/fun_sat.ml
  src/lib/reasoners/satml_frontend.ml
  src/lib/reasoners/theory.ml
  src/lib/structures/expr.ml
  src/lib/structures/symbols.ml
  src/lib/structures/symbols.mli
  src/lib/structures/xliteral.ml
  src/lib/structures/xliteral.mli
Labels: clean-up

#1305 Add a test to cover corner cases in `add_predicate`
  tests/bool/testfile-ground-predicates.ae
  tests/bool/testfile-ground-predicates.expected
Labels: testing

#1308 packaging: Avoid Cmdliner 2.0
  alt-ergo.opam
  dune-project
Labels: build

#1307 Update the installation documentation
  .github/workflows/build_js.yml
  CONTRIBUTING.md
  Makefile
  docs/sphinx_docs/Dev/index.rst
  docs/sphinx_docs/Install/index.md
  docs/sphinx_docs/Plugins/ab_why3.md
  docs/sphinx_docs/Plugins/index.md
  docs/sphinx_docs/conf.py
  docs/sphinx_docs/index.md
  docs/sphinx_docs/requirements.txt
  shell.nix
Labels: documentation
